---
- name: Setup
  hosts: all
  become: yes
  tasks:
    - set_fact:
        username: "{{ansible_hostname.split('-')[0]}}"
      tags:
        - fast
    - timezone:
        name: "US/Pacific"
        hwclock: "UTC"
      notify:
        - Restart cron
    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"
        state: present
        update_cache: yes
    - apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - docker-ce
        - emacs24-nox
        - htop
        - jq
        - python-pip
        - tig
        - tmux
        - tree
        - unzip
        - vim
        - virtualenv
      tags:
        - slow
    - get_url:
        url: https://github.com/docker/compose/releases/download/1.16.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: 0755
    - unarchive:
        src: https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
        remote_src: yes
        dest: /usr/local/bin
      tags:
        - slow
    - lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "(PasswordAuthentication) no"
        line: "\\1 yes"
        state: present
        backrefs: yes
      notify: Restart ssh
      tags:
        - ssh
    - group:
        name: "{{username}}"
        state: present
    - user:
        name: "{{ansible_user}}"
        append: yes
        groups: docker
    - user:
        name: "{{username}}"
        append: yes
        generate_ssh_key: yes
        groups: docker, sudo
        password: "{{ansible_hostname.split('-')[1] | password_hash('sha512')}}"
        shell: /bin/bash
  handlers:
    - name: Restart ssh
      service:
        name: ssh
        state: restarted
    - name: Restart cron
      service:
        name: cron
        state: restarted
        

- name: Install lab stuff
  hosts: all
  become: yes
  become_user: "{{username}}"
  tasks:
    - copy:
        src: ".gitconfig"
        dest: "/home/{{username}}/.gitconfig"
    - git:
        repo: https://github.com/christopher-demarco/ansible-class.git
        dest: /home/{{username}}/class
    - git:
        repo: https://github.com/christopher-demarco/magrathea.git
        dest: /home/{{username}}/magrathea
    - lineinfile:
        path: /home/{{username}}/magrathea/workstation/terraform.tfvars
        line: "subdomain = \"{{ansible_hostname}}.\""
        create: yes
        state: present
    - git:
        repo: https://github.com/ansible/ansible.git
        dest: /home/{{username}}/ansible
    - pip:
        requirements: /home/{{username}}/ansible/requirements.txt
        virtualenv: /home/{{username}}/.ansible_virtualenv
        state: latest
      tags:
        - slow
    - lineinfile:
        path: /home/{{username}}/.profile
        line: "{{item}}"
        state: present
      with_items:
        - alias tf=terraform
        - . .ansible_virtualenv/bin/activate
        - . ansible/hacking/env-setup

        
# magrathea:/workstation/playbook_workstation.yml
# Copyright (c) 2017 Christopher DeMarco
# Licensed under Apache License v2.0
