---
- name: Setup
  hosts: all
  become: yes
  tasks:
    - set_fact:
        my_hostname: "{{ansible_host.split('.')[0]}}"
    - set_fact:
        username: "{{my_hostname.split('-')[0]}}"
    - set_fact:
        password: "{{my_hostname.split('-')[1]}}"
    - timezone:
        name: "US/Pacific"
        hwclock: "UTC"
      notify:
        - Restart cron
    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"
        state: present
        update_cache: yes
    - apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - colordiff
        - docker-ce
        - emacs24-nox
        - htop
        - jq
        - python-pip
        - tig
        - tmux
        - tmuxinator
        - tree
        - screen
        - unzip
        - yaml-mode
        - vim
        - virtualenv
      tags:
        - slow
    - get_url:
        url: https://github.com/docker/compose/releases/download/1.16.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: 0755
    - unarchive:
        src: https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip
        remote_src: yes
        dest: /usr/local/bin
        creates: /usr/local/bin/terraform
      tags:
        - slow
    - lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "(PasswordAuthentication) no"
        line: "\\1 yes"
        state: present
        backrefs: yes
      notify: Restart ssh
      tags:
        - ssh
    - group:
        name: "{{username}}"
        state: present
    - user:
        name: "{{ansible_user}}"
        append: yes
        groups: docker
    - user:
        name: "{{username}}"
        append: yes
        generate_ssh_key: yes
        groups: docker, sudo
        password: "{{password | password_hash('sha512')}}"
        shell: /bin/bash
        update_password: on_create
      register:
        user_created
    - command: chage -d0 "{{username}}"
      when:
        user_created.changed
    - copy:
        src: "{{item}}"
        dest: "/home/{{username}}/"
        owner: "{{username}}"
      with_items:
        - .gitconfig
        - .emacs
  handlers:
    - name: Restart ssh
      service:
        name: ssh
        state: restarted
    - name: Restart cron
      service:
        name: cron
        state: restarted
        

- name: Install course materials
  hosts: all
  become: yes
  become_user: "{{username}}"
  tasks:
    - git:
        repo: https://github.com/christopher-demarco/ansible-class.git
        dest: /home/{{username}}/class
      tags:
        - git
        - slow
    - git:
        repo: https://github.com/christopher-demarco/magrathea.git
        dest: /home/{{username}}/.magrathea
      tags:
        - git
        - slow
    - git:
        repo: https://github.com/ansible/ansible.git
        dest: /home/{{username}}/ansible
      tags:
        - git
        - slow
    - lineinfile:
        path: /home/{{username}}/.magrathea/workstation/terraform.tfvars
        line: "{{item}}"
        create: yes
        state: present
      with_items:
        - "subdomain = \"{{my_hostname}}.\""
    - pip:
        requirements: /home/{{username}}/ansible/requirements.txt
        virtualenv: /home/{{username}}/.ansible_virtualenv
        state: latest
      tags:
        - slow
    - file:
        src: /home/{{username}}/.magrathea/workstation/inventory.py
        dest: /home/{{username}}/class/inventory.py
        state: link
    - lineinfile:
        path: /home/{{username}}/.profile
        line: "{{item}}"
        state: present
      with_items:
        - alias tf=terraform
        - alias em=emacs
        - . .ansible_virtualenv/bin/activate
        - . ansible/hacking/env-setup
        - export MAGRATHEA_STATE=/home/{{username}}/.magrathea/workstation
        - export ANSIBLE_USER=ubuntu
        - export ANSIBLE_SSH_PRIVATE_KEY_FILE=/home/{{username}}/.ssh/id_rsa
    - file:
        src: /home/{{username}}/.ssh/id_rsa
        dest: /home/{{username}}/.magrathea/workstation/keys/magrathea
        state: link
    - file:
        src: /home/{{username}}/.ssh/id_rsa.pub
        dest: /home/{{username}}/.magrathea/workstation/keys/magrathea.pub
        state: link
    - copy:
        src: keys/.aws/
        dest: /home/{{username}}/.aws
    - file:
        src: /home/{{username}}/.magrathea/workstation/recreate_alpha.sh
        dest: /home/{{username}}/recreate_alpha.sh
        state: link
    # - command: docker pull {{ item }}
    #   with_items:
    #     - "python:2-alpine"
    #     - "python:2.7-jessie"
    #     - "ubuntu:zesty"
    #   tags:
    #     - slow
    # - command: /home/{{username}}/recreate_alpha.sh
    #   args:
    #     creates: /home/{{username}}/.magrathea/workstation/terraform.tfstate
    #   tags:
    #     - slow



      
        


# magrathea:/workstation/playbook_workstation.yml
# Copyright (c) 2017 Christopher DeMarco
# Licensed under Apache License v2.0
